version: '3'

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "app"
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
